#!/bin/bash -e

# script to cleanup all home directories of training users so they start fresh

echo "This script will delete files from all training user home directories"
echo "This will likely disrupt any training users currently running an app"
echo "Type \"yes\" if you wish to continue: "
read -r line
if [ "${line}" = "yes" ]; then
    # perform deletions
    echo "Cleaning training user homes..."
    

else
    exit 1
fi
